version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.10
    steps:
      - checkout
      - run:
          name: Installing all dependencies
          command: npm install
      - run:
          name: Build and deploy to staging server
          command: |
            npm build
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN_INTERNAL --only hosting:user-dashboard --non-interactive

workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
